name: Example of Reusable workflow 

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:

    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 #     - uses: ./.github/workflows/reusable/action
 #       with:
 #         username: ${{ inputs.username }}
#        token: ${{ secrets.token }}
      - run: echo "Checkout was done already"
      - run: pwd
      - run: ls -la 
      - run: echo ${{ inputs.username }}
      - run: echo ${{ secrets.token }}